# Generated by Django 5.2.4 on 2026-07-01 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Producto')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio del Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen del Producto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_nombre_producto'), models.Index(fields=['precio'], name='idx_precio_producto')],
                'constraints': [models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='check_precio_no_negativo')],
            },
        ),
    ]
